<?php
session_start();

echo "<script language=\"JavaScript\" type=\"text/javascript\">";
echo "function chkhost()";
echo "{";
echo "if (document.getElementById(\"hostname\").value == 'false')";
echo "{";
echo "document.getElementById(\"hostname\").checked = 'checked';";
echo "document.getElementById(\"host\").style.visibility = 'visible';";
echo "document.getElementById(\"hostname\").value = 'true';";
echo "}";
echo "else {";
echo "document.getElementById(\"hostname\").checked = '';";
echo "document.getElementById(\"host\").style.visibility = 'hidden';";
echo "document.getElementById(\"hostname\").value = 'false';";
echo "}";
echo "}";
echo "function chkdomain()";
echo "{";
echo "if (document.getElementById(\"domainname\").value == 'false')";
echo "{";
echo "document.getElementById(\"domainname\").checked = 'checked';";
echo "document.getElementById(\"domain\").style.visibility = 'visible';";
echo "document.getElementById(\"domainname\").value = 'true';";
echo "}";
echo "else {";
echo "document.getElementById(\"domainname\").checked = '';";
echo "document.getElementById(\"domain\").style.visibility = 'hidden';";
echo "document.getElementById(\"domainname\").value = 'false';";
echo "}";
echo "}";
echo "function chkip()";
echo "{";
echo "if (document.getElementById(\"ipaddress\").value == 'false')";
echo "{";
echo "document.getElementById(\"ipaddress\").checked = 'checked';";
echo "document.getElementById(\"ip\").style.visibility = 'visible';";
echo "document.getElementById(\"ipaddress\").value = 'true';";
echo "}";
echo "else {";
echo "document.getElementById(\"ipaddress\").checked = '';";
echo "document.getElementById(\"ip\").style.visibility = 'hidden';";
echo "document.getElementById(\"ipaddress\").value = 'false';";
echo "}";
echo "}";
echo "function chkmac()";
echo "{";
echo "if (document.getElementById(\"hwaddress\").value == 'false')";
echo "{";
echo "document.getElementById(\"hwaddress\").checked = 'checked';";
echo "document.getElementById(\"mac\").style.visibility = 'visible';";
echo "document.getElementById(\"hwaddress\").value = 'true';";
echo "}";
echo "else {";
echo "document.getElementById(\"hwaddress\").checked = '';";
echo "document.getElementById(\"mac\").style.visibility = 'hidden';";
echo "document.getElementById(\"hwaddress\").value = 'false';";
echo "}";
echo "}";
echo "function chkadd()";
echo "{";
echo "if (document.getElementById(\"additional\").value == 'false')";
echo "{";
echo "document.getElementById(\"add\").innerHTML = document.getElementById(\"addtext\").value;";
echo "document.getElementById(\"additional\").checked = 'checked';";
echo "document.getElementById(\"add\").style.visibility = 'visible';";
echo "document.getElementById(\"additional\").value = 'true';";
echo "}";
echo "else {";
echo "document.getElementById(\"add\").innerHTML = document.getElementById(\"addtext\").value;";
echo "document.getElementById(\"additional\").checked = '';";
echo "document.getElementById(\"add\").style.visibility = 'hidden';";
echo "document.getElementById(\"additional\").value = 'false';";
echo "}";
echo "}";

echo "</script>";

echo "<div class=\"preview\">";
echo "<table width=\"400\" height=\"200\">";
echo "<tr>";
echo "<td>";
echo "RZ-LOGO";
echo "</td>";
echo "</tr>";
echo "<tr>";
echo "<td align=\"center\">";
echo "<b><span id=\"host\">Host1</span></b>";
echo "</td>";
echo "<td rowspan=\"6\" width=\"100\">";
echo "<img src=\"semacode.png\" />";
echo "</td>";
echo "</tr>";
echo "<tr>";
echo "<td align=\"center\">";
echo "<span id=\"domain\">host1.uni-freiburg.de</span>";
echo "</td>";
echo "</tr>";
echo "<tr>";
echo "<td align=\"center\">";
echo "<b><i><span id=\"ip\">132.230.200.200</span></i></b>";
echo "</td>";
echo "</tr>";
echo "<tr>";
echo "<td align=\"center\">";
echo "<span id=\"mac\">00:10:11:4E:2B:84</span>";
echo "</td>";
echo "</tr>";
echo "<tr>";
echo "<td align=\"center\">";
echo "<span id=\"add\">Zusatztext</span>";
echo "</td>";
echo "</tr>";
echo "</table>";
echo "</div>";

echo "<form method=\"POST\" action=\"generatePDF.php\">";
echo "<div class=\"options\">";
echo "<input type=\"checkbox\" id=\"hostname\" name=\"hostname\" onclick=\"chkhost()\" value=\"true\" checked=\"checked\" />";
echo "Hostname";
echo "<br />";
echo "<input type=\"checkbox\" id=\"domainname\" name=\"domainname\" onclick=\"chkdomain()\" value=\"true\" checked=\"checked\" />";
echo "Domainname";
echo "<br />";
echo "<input type=\"checkbox\" id=\"ipaddress\" name=\"ipaddress\" onclick=\"chkip()\" value=\"true\" checked=\"checked\" />";
echo "IP-Adresse";
echo "<br />";
echo "<input type=\"checkbox\" id=\"hwaddress\" name=\"hwaddress\" onclick=\"chkmac()\" value=\"true\" checked=\"checked\" />";
echo "MAC-Adresse";
echo "<br />";
echo "<input type=\"checkbox\" id=\"additional\" name=\"additional\" onclick=\"chkadd()\" value=\"true\" checked=\"checked\" />";
echo "Zusatzinfo";
echo "<input type=\"text\" id=\"addtext\" name=\"addtext\" />";
echo "Schriftgroesse Zusatztext:";
echo "<select name=\"addsize\" size=\"1\">";
echo "<option>6</option>";
echo "<option>7</option>";
echo "<option>8</option>";
echo "<option>9</option>";
echo "<option>10</option>";
echo "<option>11</option>";
echo "<option>12</option>";
echo "<option>13</option>";
echo "<option>14</option>";
echo "<option>15</option>";
echo "<option>16</option>";
echo "<option>17</option>";
echo "<option>18</option>";
echo "<option>19</option>";
echo "<option>20</option>";
echo "</select>";
echo "</div>";

echo "<div class=\"generate\">";
echo "Positionen auf dem PDF:";
echo "<br />";
echo "<table width=\"200\" bgcolor=\"#000000\" cellpadding=\"1\" cellspacing=\"1\">";
echo "<tr>";
echo "<td bgcolor=\"#FFFFFF\">Position 0</td>";
echo "<td bgcolor=\"#FFFFFF\">Position 1</td>";
echo "</tr>";
echo "<tr>";
echo "<td bgcolor=\"#FFFFFF\">Position 2</td>";
echo "<td bgcolor=\"#FFFFFF\">Position 3</td>";
echo "</tr>";
echo "<tr>";
echo "<td bgcolor=\"#FFFFFF\">Position 4</td>";
echo "<td bgcolor=\"#FFFFFF\">Position 5</td>";
echo "</tr>";
echo "<tr>";
echo "<td bgcolor=\"#FFFFFF\">Position 6</td>";
echo "<td bgcolor=\"#FFFFFF\">Position 7</td>";
echo "</tr>";
echo "<tr>";
echo "<td bgcolor=\"#FFFFFF\">Position 8</td>";
echo "<td bgcolor=\"#FFFFFF\">Position 9</td>";
echo "</tr>";
echo "</table>";
echo "<br />";
echo "Ab Postition: ";
echo "<select name=\"position\" size=\"1\">";
echo "<option>0</option>";
echo "<option>1</option>";
echo "<option>2</option>";
echo "<option>3</option>";
echo "<option>4</option>";
echo "<option>5</option>";
echo "<option>6</option>";
echo "<option>7</option>";
echo "<option>8</option>";
echo "<option>9</option>";
echo "</select>";
echo "<br />";
echo "<input type=\"submit\" name=\"submit\" value=\"Generate\">";
echo "</form>";
echo "</div>";
