#!/bin/sh
#
# Description:  configuration script for Debian/Sarge to configure
#		linux diskless clients (executed within initial
#		ramdisk after genconfig) 
#
# Author(s):    Dirk von Suchodoletz <dirk@goe.net>, 13-12-2005
#		Blabla
#		Blub
#
# Copyright:    (c) 2003, 2005 - RZ Universitaet Freiburg
# 
# Version:      0.3.5k

# check for configuration files to source

# ldap, dhcp, file


