#!/bin/sh
# Copyright (c) 2008..2009 - OpenSLX GmbH
#
# This program is free software distributed under the GPL version 2.
# See http://openslx.org/COPYING
#
# If you have any feedback please consult http://openslx.org/feedback and
# send your feedback to feedback@openslx.org
#
# General information about OpenSLX can be found under http://openslx.org
#
# Wrapper script for OpenSLX environments used with server and client stage4 

SLX_PATH=/opt/openslx/share
SLX_UCLIB_PATH=$SLX_PATH/uclib-rootfs

if [ -f /opt/openslx/share/uclib-rootfs ]; then
  SLX_UCLIB_PATH=/opt/openslx/share/uclib-rootfs
elif [ -f /opt/openslx/uclib-rootfs ]; then
  SLX_UCLIB_PATH=/opt/openslx/uclib-rootfs
else
  echo "Can't find OpenSLX Environment." && exit 1
fi

[ -f /lib/ld-uClibc.so.0 ] && ln -sf $SLX_PATH/uclib-rootfs/lib/ld-uClibc.so.0

PATH=$SLX_UCLIB_PATH/bin:$SLX_UCLIB_PATH/usr/bin:$SLX_UCLIB_PATH/sbin:\
$SLX_UCLIB_PATH/usr/sbin
LD_LIBRARY_PATH=$SLX_UCLIB_PATH/lib:$SLX_UCLIB_PATH/usr/lib 
LD_LIBRARY_PATH=$LD_LIBRARY_PATH PATH=$PATH PS1="#" $@
