#!/bin/sh
#
# Description: startgui runs as script replacement for xinit
#
# Author(s):    Dirk von Suchodoletz <dirk@goe.net>, 19-05-2006
#		Michael Janczyk, 28-09-2007
# Copyright:    (c) 2003, 2007 - RZ Universitaet Freiburg
#
# Version:      0.1.0c
#
# /var/X11R6/bin/startgui
# 
###########################################################################

WM=$1
[ $WM ] || WM=kde
case "$WM" in
  *fvwm*)
    fvwm2
  ;;
  *kde*)
    startkde
  ;;
  *wmaker*|*windowmaker*)
    wmaker
  ;;
  *ice*)
    icewm
  ;;
  *gnome*)
    gnome
  ;;
  *citrix|Citrix|ICAClient|*wfica)
    wfica
  ;;
  *citrix-mgr|*citrix-indirect|*wfcmgr)
    #
  ;;
  *vmware*)
    /var/X11R6/bin/xdialog.sh
  ;;
  *)
    if which $WM; then
      $WM
      error "Session ended ... Click OK to restart X" xmessage
    else
      error "Tried: $WM - Kein sinnvoller wm angegeb." xmessage
      xterm
    fi
  ;;
esac
exit 0
