#!/bin/sh
#
# Description:  universal (distro independent) configuration script
#		for linux diskless clients (executed within initial
#		ramdisk) 
#
# Author(s):    Dirk von Suchodoletz <dirk@goe.net>, 06-01-2006
#		Blabla
#		Blub
#
# Copyright:    (c) 2003, 2005 - RZ Universitaet Freiburg
# 
# Version:      0.0.1a

# check for configuration files to source

# functions common for all distros
. /etc/functions
# configuration settings (several file and directory variables)
. /etc/sysconfig/config

# 

# ldap, dhcp, file


