// generated by Fast Light User Interface Designer (fluid) version 2.1000

#ifndef MessageWindow_h
#define MessageWindow_h
#include <fltk/Window.h>
extern fltk::Window* win;
#include <fltk/Clock.h>
#include <fltk/TextDisplay.h>
extern fltk::TextDisplay* w_text;
#endif
