// generated by Fast Light User Interface Designer (fluid) version 2.1000

#include "MessageWindow.h"
#include <iostream>
#include <string>
#include <csignal>
#include <fltk/run.h>

fltk::Window *win=(fltk::Window *)0;
fltk::TextDisplay *w_text=(fltk::TextDisplay *)0;




void sig_handler(int sig) {
  // just terminate after 10 seconds
  // here we could change the text after each second ;-)
  exit(0);
}

int main (int argc, char **argv) {

  if(argc < 2 ) {
    std::cout << "Please give some message to display!" << std::endl;
    exit(1);
  }

  fltk::Window* w;
  {
    fltk::Window* o = win = new fltk::Window(510, 160);
    o->border(false);
    w = o;
    o->shortcut(0xff1b);
    o->begin();
    {
      fltk::Clock* o = new fltk::Clock(5, 5, 155, 150);
      o->labelsize(16);
      o->tooltip("Aktuelle Uhrzeit des Rechners");
    }
    {
      fltk::TextDisplay* o = w_text = new fltk::TextDisplay(165, 5, 340, 150);
      fltk::TextBuffer* buf = new fltk::TextBuffer();
      buf->text(argv[1]);
      o->tooltip("Dieses Fenster schließt automatisch nach 10 Sekunden");
      o->buffer(buf);
      o->box(fltk::UP_BOX);
      o->color((fltk::Color)0xe0e0e000);
      o->selection_textcolor((fltk::Color)0xffffff00);
      o->labelsize(16);
      o->textsize(16);
      o->wrap_mode(true);
    }
    o->end();
    o->resizable(o);
  }

  // set an alarm after 10 seconds
  alarm(10);
  signal(SIGALRM, sig_handler);

  w->show();
  return  fltk::run();
}
